/* NHT Accounting Reconciliation V2 - 2026-10-08 */
(function(){
'use strict';
const V2='2.0.0';
function q(id){return document.getElementById(id)}
function num(v){return Number(v||0)||0}
function txt(v){return String(v??'').trim()}
function maxAbs(a,b){return Math.abs(num(b))>Math.abs(num(a))?num(b):num(a)}
function ym(v){const s=txt(v);if(!s)return '';let m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/);if(m)return m[3]+'-'+String(m[2]).padStart(2,'0');m=s.match(/(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})/);if(m)return m[1]+'-'+String(m[2]).padStart(2,'0');return ''}
function dateKey(v){const s=txt(v);if(!s)return '';let m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/);if(m)return m[3]+'-'+String(m[2]).padStart(2,'0')+'-'+String(m[1]).padStart(2,'0');m=s.match(/(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})/);if(m)return m[1]+'-'+String(m[2]).padStart(2,'0')+'-'+String(m[3]).padStart(2,'0');return ''}
function inPeriod(v,from,to){const d=dateKey(v);if(!d)return false;if(from&&d<from)return false;if(to&&d>to)return false;return true}
function hasDelivered(order){const s=txt(order?.order_status).toLowerCase();return !!order?.delivered||s.includes('delivered')||s.includes('đã giao')||s.includes('hoàn tất')||s.includes('completed')}
function statusNeedsAdjustment(r){const s=txt(r.order_status).toLowerCase();return num(r.order_refund_amount)>0||num(r.return_qty)>0||/refund|return|cancel|hoàn|trả|hủy/.test(s)}
function feeTotal(r){return num(r.transaction_fee)+num(r.tiktok_commission)+num(r.processing_fee)+num(r.shipping_net)+num(r.affiliate)+num(r.partner)}
function sourceLabel(r){if(r.order_source_present&&r.income_source_present)return 'Đơn hàng + Income';if(r.order_source_present)return 'Chỉ Đơn hàng';if(r.income_source_present)return 'Chỉ Income';return 'Không rõ'}
function accountingSuggestion(r){const parts=[];if(r.revenue_in_period)parts.push('Doanh thu/HĐ: N131-Sàn / C511,C3331');if(r.income_source_present&&Math.abs(feeTotal(r))>0)parts.push('Phí sàn: N641/642 (chi tiết từng phí) / C131-Sàn');if(r.income_source_present&&Math.abs(num(r.settlement))>0)parts.push('Quyết toán: N112 / C131-Sàn');return parts.join(' · ')}
function invoiceStateV2(r){const tol=typeof invoiceTolerance==='function'?invoiceTolerance():1;if(!r.order_source_present)return 'CHỜ FILE ĐƠN GỐC';if(!r.revenue_in_period)return 'NGOÀI KỲ DOANH THU';const req=num(r.required_invoice),eff=num(r.invoice_effective_amount),first=num(r.invoice_original_issued_amount),adj=num(r.invoice_adjustment_amount),count=num(r.invoice_count);if(count===0)return Math.abs(req)>tol?'CHƯA XUẤT HĐ':'KHÔNG PHÁT SINH';const diff=eff-req;if(Math.abs(diff)<=tol){if(Math.abs(adj)>tol)return 'ĐÃ ĐIỀU CHỈNH - KHỚP';return 'KHỚP'}if(statusNeedsAdjustment(r)&&Math.abs(adj)<=tol&&Math.abs(first-req)>tol)return 'CẦN ĐIỀU CHỈNH';return diff>tol?'DƯ HĐ':'THIẾU HĐ'}
function riskV2(r){const tol=typeof invoiceTolerance==='function'?invoiceTolerance():1;const st=txt(r.invoice_state_v2);if(['CHƯA XUẤT HĐ','DƯ HĐ','THIẾU HĐ','CẦN ĐIỀU CHỈNH','CHỜ FILE ĐƠN GỐC'].includes(st))return 'CAO';if(Math.abs(num(r.settlement_diff))>tol)return 'CAO';if(r.order_source_present&&r.income_source_present&&Math.abs(num(r.orders_income_diff))>tol)return 'TRUNG BÌNH';if((r.revenue_in_period&&!r.delivered)||(!r.created&&!r.income_order_date))return 'TRUNG BÌNH';return 'THẤP'}
function actionV2(r){switch(r.invoice_state_v2){case 'CHƯA XUẤT HĐ':return 'Lập hóa đơn cho đơn đã giao';case 'DƯ HĐ':return 'Rà soát hóa đơn xuất dư / cần điều chỉnh giảm';case 'THIẾU HĐ':return 'Rà soát hóa đơn thiếu / cần điều chỉnh tăng';case 'CẦN ĐIỀU CHỈNH':return 'Lập hóa đơn điều chỉnh theo vòng đời đơn';case 'CHỜ FILE ĐƠN GỐC':return 'Giữ Income trong dữ liệu năm; chờ file đơn tháng gốc';case 'ĐÃ ĐIỀU CHỈNH - KHỚP':return 'Đã xử lý, lưu hồ sơ đối chiếu';case 'KHỚP':return 'Không cần xử lý';default:return ''}}

parseOrdersForEngine=async function(file){
 let headers=null,map=null,orderMap=new Map(),rowCount=0;const known=['Order ID','Order Status','Created Time','Delivered Time','Order Amount'];
 await forEachTableRow(file,['OrderSKUList','Tất cả đơn hàng','Sheet1'],async(rn,row)=>{
   if(!headers){const hm=makeHeaderMap(row);if(hasAnyHeader(hm,known)){headers=row;map=hm;return}if(rn<20)return;headers=row;map=hm;return}
   const id=normalizeId(getBy(row,map,['Order ID','Mã đơn hàng','order_id']));if(!id||id==='Order ID')return;rowCount++;
   let a=orderMap.get(id);if(!a){a={order_id:id,order_status:'',created:'',delivered:'',creator:'',qty:0,return_qty:0,sku_revenue:0,order_shipping_buyer:0,order_amount:0,order_refund_amount:0,order_net_amount:0,order_source_rows:0};orderMap.set(id,a)}
   a.order_source_rows++;const st=normalizeText(getBy(row,map,['Order Status','Trạng thái đơn']));if(st)a.order_status=st;
   const cr=excelDateToString(getBy(row,map,['Created Time','Thời gian tạo đơn','Ngày tạo đơn']));const dl=excelDateToString(getBy(row,map,['Delivered Time','Ngày đã giao','Ngày giao thành công']));
   if(cr&&(!a.created||dateKey(cr)<dateKey(a.created)))a.created=cr;if(dl&&(!a.delivered||dateKey(dl)>dateKey(a.delivered)))a.delivered=dl;
   const creator=normalizeText(getBy(row,map,['Creator Handle','Affiliate ID','Creator ID']));if(creator)a.creator=creator;
   a.qty+=nval(getBy(row,map,['Quantity','Số lượng']));a.return_qty+=nval(getBy(row,map,['Sku Quantity of return','SKU Quantity of return','Số lượng trả']));
   a.sku_revenue+=nval(getBy(row,map,['SKU Subtotal After Discount','SKU Subtotal after discount','Doanh thu sau giảm giá']));
   a.order_shipping_buyer=maxAbs(a.order_shipping_buyer,nval(getBy(row,map,['Shipping Fee After Discount','Phí vận chuyển sau giảm giá'])));
   a.order_amount=maxAbs(a.order_amount,nval(getBy(row,map,['Order Amount','Giá trị đơn hàng'])));
   a.order_refund_amount=maxAbs(a.order_refund_amount,nval(getBy(row,map,['Order Refund Amount','Giá trị hoàn đơn'])));
 },n=>setRunMessage('Đang đọc Tất cả đơn hàng: '+n.toLocaleString('vi-VN')+' dòng...'));
 if(!headers)throw new Error('Không tìm thấy dòng tiêu đề trong file Tất cả đơn hàng.');
 for(const a of orderMap.values()){const gross=Math.abs(a.order_amount)>0?a.order_amount:(a.sku_revenue+a.order_shipping_buyer);a.order_net_amount=gross-Math.abs(a.order_refund_amount);a.revenue_month=ym(a.delivered);a.order_month=ym(a.created)}
 return {map:orderMap,count:rowCount,headers};
};

parseIncomeForEngine=async function(file){
 let headers=null,map=null,agg=new Map(),count=0;const expected=['ID đơn hàng/điều chỉnh','Tổng phụ sau giảm giá của người bán','Tổng số tiền quyết toán'];
 await forEachTableRow(file,['Chi tiết đơn hàng','Order details','Sheet1'],async(rn,row)=>{
   if(!headers){const hm=makeHeaderMap(row);if(hasAnyHeader(hm,expected)){headers=row;map=hm;return}if(rn<30)return}
   if(!map)return;const id=normalizeId(getBy(row,map,['ID đơn hàng/điều chỉnh','Order ID','Mã đơn hàng']));if(!id||id==='ID đơn hàng/điều chỉnh')return;count++;
   let a=agg.get(id);if(!a){a={order_id:id,seller_revenue:0,seller_refund:0,seller_net:0,buyer_shipping_income:0,buyer_shipping_refund:0,buyer_shipping_net:0,transaction_fee:0,tiktok_commission:0,processing_fee:0,shipping_actual:0,shipping_platform_discount:0,failed_delivery_subsidy:0,return_shipping_actual:0,shipping_net:0,affiliate_base:0,affiliate_ads:0,affiliate:0,partner_base:0,partner_ads:0,partner:0,adjustment:0,settlement:0,total_fee_source:0,income_order_date:'',settlement_date:'',income_source_rows:0};agg.set(id,a)}
   a.income_source_rows++;const v=(...names)=>nval(getBy(row,map,names));
   a.seller_revenue+=v('Tổng phụ sau giảm giá của người bán');a.seller_refund+=v('Tổng phụ của khoản hoàn tiền sau giảm giá của người bán','Tổng phụ khoản hoàn tiền sau giảm giá của người bán');
   a.buyer_shipping_income+=v('Chi phí vận chuyển của khách hàng');a.buyer_shipping_refund+=v('Phí vận chuyển của khách hàng được hoàn lại');
   a.transaction_fee+=v('Phí giao dịch');a.tiktok_commission+=v('Phí hoa hồng của TikTok Shop');a.processing_fee+=v('Phí xử lý đơn hàng');
   a.shipping_actual+=v('Phí vận chuyển thực tế');a.shipping_platform_discount+=v('Chiết khấu phí vận chuyển của nền tảng');a.failed_delivery_subsidy+=v('Trợ cấp giao hàng không thành công');a.return_shipping_actual+=v('Phí vận chuyển trả hàng thực tế');
   a.affiliate_base+=v('Hoa hồng liên kết');a.affiliate_ads+=v('Hoa hồng liên kết Quảng cáo cửa hàng');a.partner_base+=v('Hoa hồng của đối tác liên kết');a.partner_ads+=v('Hoa hồng quảng cáo cửa hàng của Đối tác liên kết');
   a.adjustment+=v('Số tiền điều chỉnh');a.settlement+=v('Tổng số tiền quyết toán');a.total_fee_source+=v('Tổng phí');
   const od=getBy(row,map,['Thời gian tạo đơn hàng','Ngày tạo đơn hàng','Order Created Time','Created Time','Ngày đơn hàng']);const sd=getBy(row,map,['Thời gian quyết toán đơn hàng','Settlement Time','Ngày quyết toán']);
   const ods=excelDateToString(od),sds=excelDateToString(sd);if(ods&&(!a.income_order_date||dateKey(ods)<dateKey(a.income_order_date)))a.income_order_date=ods;if(sds&&(!a.settlement_date||dateKey(sds)>dateKey(a.settlement_date)))a.settlement_date=sds;
 },n=>setRunMessage('Đang đọc Income: '+n.toLocaleString('vi-VN')+' dòng...'));
 if(!headers)throw new Error('Không tìm thấy tiêu đề file Income.');
 for(const a of agg.values()){a.seller_net=a.seller_revenue+a.seller_refund;a.buyer_shipping_net=a.buyer_shipping_income+a.buyer_shipping_refund;a.shipping_net=a.shipping_actual+a.shipping_platform_discount+a.failed_delivery_subsidy+a.return_shipping_actual;a.affiliate=a.affiliate_base+a.affiliate_ads;a.partner=a.partner_base+a.partner_ads;a.required_invoice_income=a.seller_net+a.buyer_shipping_net;a.order_month=ym(a.income_order_date);a.settlement_month=ym(a.settlement_date)}
 return {map:agg,count,headers};
};

buildLiveRows=function(orders,incomes,invoices){
 const meta=currentPeriodMeta();const ids=new Set([...orders.keys(),...incomes.keys(),...invoices.keys()]);const rows=[];
 for(const id of ids){const ord=orders.get(id)||null,inc=incomes.get(id)||null,inv=invoices.get(id)||null;
   const r={order_id:id,order_source_present:!!ord,income_source_present:!!inc,order_status:ord?.order_status||'',created:ord?.created||inc?.income_order_date||'',delivered:ord?.delivered||'',creator:ord?.creator||'',qty:num(ord?.qty),return_qty:num(ord?.return_qty),sku_revenue:num(ord?.sku_revenue),order_shipping_buyer:num(ord?.order_shipping_buyer),order_amount:num(ord?.order_amount),order_refund_amount:num(ord?.order_refund_amount),order_net_amount:num(ord?.order_net_amount),seller_revenue:num(inc?.seller_revenue),seller_refund:num(inc?.seller_refund),seller_net:num(inc?.seller_net),buyer_shipping_income:num(inc?.buyer_shipping_income),buyer_shipping_refund:num(inc?.buyer_shipping_refund),buyer_shipping_net:num(inc?.buyer_shipping_net),transaction_fee:num(inc?.transaction_fee),tiktok_commission:num(inc?.tiktok_commission),processing_fee:num(inc?.processing_fee),shipping_actual:num(inc?.shipping_actual),shipping_platform_discount:num(inc?.shipping_platform_discount),failed_delivery_subsidy:num(inc?.failed_delivery_subsidy),return_shipping_actual:num(inc?.return_shipping_actual),shipping_net:num(inc?.shipping_net),affiliate_base:num(inc?.affiliate_base),affiliate_ads:num(inc?.affiliate_ads),affiliate:num(inc?.affiliate),partner_base:num(inc?.partner_base),partner_ads:num(inc?.partner_ads),partner:num(inc?.partner),adjustment:num(inc?.adjustment),settlement:num(inc?.settlement),total_fee_source:num(inc?.total_fee_source),income_order_date:inc?.income_order_date||'',settlement_date:inc?.settlement_date||'',invoice_count:num(inv?.invoice_count),invoice_amount_all:num(inv?.invoice_amount_all),invoice_new_amount:num(inv?.invoice_new_amount),invoice_adjustment_amount:num(inv?.invoice_adjustment_amount),invoice_active_net:num(inv?.invoice_active_net),invoice_no:inv?.invoice_no?.join(', ')||'',invoice_date:inv?.invoice_date?.join(', ')||'',invoice_statuses:inv?[...inv.statuses].join(' | '):'',invoice_items:inv?.invoice_items||[],source_period:meta.period||'',source_from:meta.from||'',source_to:meta.to||''};
   if(typeof recomputeInvoiceFromItems==='function')recomputeInvoiceFromItems(r);
   r.revenue_in_period=!!ord&&hasDelivered(ord)&&inPeriod(r.delivered,meta.from,meta.to);r.income_in_period=!!inc;r.order_month=ym(r.created||r.income_order_date);r.revenue_month=ym(r.delivered);r.settlement_month=ym(r.settlement_date);
   const orderBasis=Math.abs(r.order_net_amount)>0?r.order_net_amount:(r.sku_revenue+r.order_shipping_buyer);r.required_invoice=orderBasis;r.required_invoice_income=r.seller_net+r.buyer_shipping_net;r.orders_income_diff=r.required_invoice_income-r.required_invoice;
   r.total_fee_calc=feeTotal(r);r.settlement_calc=r.required_invoice_income+r.total_fee_calc+r.adjustment;r.settlement_diff=r.settlement-r.settlement_calc;r.invoice_compare_value=num(r.invoice_effective_amount||r.invoice_active_net||r.invoice_amount_all);r.invoice_diff=r.invoice_compare_value-r.required_invoice;
   r.invoice_state_v2=invoiceStateV2(r);r.risk_level=riskV2(r);r.accounting_action=actionV2(r);r.accounting_suggestion=accountingSuggestion(r);r.source_state=sourceLabel(r);r.result=r.invoice_state_v2;rows.push(r);
 }
 return rows;
};

mergePeriodRows=function(periods){
 const m=new Map();const incomeNums=['seller_revenue','seller_refund','seller_net','buyer_shipping_income','buyer_shipping_refund','buyer_shipping_net','transaction_fee','tiktok_commission','processing_fee','shipping_actual','shipping_platform_discount','failed_delivery_subsidy','return_shipping_actual','shipping_net','affiliate_base','affiliate_ads','affiliate','partner_base','partner_ads','partner','adjustment','settlement','total_fee_source'];
 for(const p of periods){for(const src of(p.rows||[])){const id=txt(src.order_id);if(!id)continue;let r=m.get(id);if(!r){r={order_id:id,order_source_present:false,income_source_present:false,order_status:'',created:'',delivered:'',creator:'',qty:0,return_qty:0,sku_revenue:0,order_shipping_buyer:0,order_amount:0,order_refund_amount:0,order_net_amount:0,income_order_date:'',settlement_date:'',invoice_items:[],income_events:[],invoice_events:[],periods:[],_invoiceKeys:new Set()};incomeNums.forEach(k=>r[k]=0);m.set(id,r)}
   if(src.order_source_present||src.order_status||src.delivered){r.order_source_present=true;if(src.order_status)r.order_status=src.order_status;if(src.created&&(!r.created||dateKey(src.created)<dateKey(r.created)))r.created=src.created;if(src.delivered&&(!r.delivered||dateKey(src.delivered)>dateKey(r.delivered)))r.delivered=src.delivered;if(src.creator)r.creator=src.creator;r.qty=Math.max(num(r.qty),num(src.qty));r.return_qty=Math.max(num(r.return_qty),num(src.return_qty));r.sku_revenue=maxAbs(r.sku_revenue,src.sku_revenue);r.order_shipping_buyer=maxAbs(r.order_shipping_buyer,src.order_shipping_buyer);r.order_amount=maxAbs(r.order_amount,src.order_amount);r.order_refund_amount=maxAbs(r.order_refund_amount,src.order_refund_amount);r.order_net_amount=maxAbs(r.order_net_amount,src.order_net_amount)}
   if(src.income_source_present||incomeNums.some(k=>Math.abs(num(src[k]))>0)){r.income_source_present=true;incomeNums.forEach(k=>r[k]+=num(src[k]));if(src.income_order_date&&(!r.income_order_date||dateKey(src.income_order_date)<dateKey(r.income_order_date)))r.income_order_date=src.income_order_date;if(src.settlement_date&&(!r.settlement_date||dateKey(src.settlement_date)>dateKey(r.settlement_date)))r.settlement_date=src.settlement_date;r.income_events.push({period_id:p.id,period:p.period,order_date:src.income_order_date||src.created||'',settlement_date:src.settlement_date||'',seller_net:num(src.seller_net),buyer_shipping_net:num(src.buyer_shipping_net),transaction_fee:num(src.transaction_fee),tiktok_commission:num(src.tiktok_commission),processing_fee:num(src.processing_fee),shipping_net:num(src.shipping_net),affiliate:num(src.affiliate),partner:num(src.partner),adjustment:num(src.adjustment),settlement:num(src.settlement)})}
   r.periods.push(p.period);const arr=typeof legacyInvoiceItemsFromRow==='function'?legacyInvoiceItemsFromRow(src):(src.invoice_items||[]);for(const it0 of arr){const it={...it0,period:p.period,period_id:p.id};const key=[it.no||'',it.date||'',it.status||'',num(it.amount)].join('|');if(!r._invoiceKeys.has(key)){r._invoiceKeys.add(key);r.invoice_items.push(it);r.invoice_events.push(it)}}
 }}
 return [...m.values()].map(r=>{delete r._invoiceKeys;r.periods=[...new Set(r.periods.filter(Boolean))];if(typeof recomputeInvoiceFromItems==='function')recomputeInvoiceFromItems(r);r.created=r.created||r.income_order_date||'';r.order_month=ym(r.created);r.revenue_month=ym(r.delivered);r.settlement_month=ym(r.settlement_date);r.required_invoice=Math.abs(r.order_net_amount)>0?r.order_net_amount:(r.sku_revenue+r.order_shipping_buyer);r.required_invoice_income=r.seller_net+r.buyer_shipping_net;r.orders_income_diff=r.required_invoice_income-r.required_invoice;r.total_fee_calc=feeTotal(r);r.settlement_calc=r.required_invoice_income+r.total_fee_calc+r.adjustment;r.settlement_diff=r.settlement-r.settlement_calc;r.invoice_compare_value=num(r.invoice_effective_amount||r.invoice_active_net||r.invoice_amount_all);r.invoice_diff=r.invoice_compare_value-r.required_invoice;r.revenue_in_period=!!r.order_source_present&&hasDelivered(r);r.income_in_period=!!r.income_source_present;r.invoice_state_v2=invoiceStateV2(r);r.risk_level=riskV2(r);r.accounting_action=actionV2(r);r.accounting_suggestion=accountingSuggestion(r);r.source_state=sourceLabel(r);r.result=r.invoice_state_v2;return r});
};

runReconciliation=async function(){
 const missing=[];const req=requiredUploadKeys();if(req.includes('orders')&&!uploadedFiles.orders)missing.push('Tất cả đơn hàng');if(req.includes('income')&&!uploadedFiles.income)missing.push('Income');if(req.includes('invoice')&&!uploadedFiles.invoice)missing.push('Danh sách hóa đơn');if(req.includes('statement')&&!uploadedFiles.statement)missing.push('Sao kê sàn');if(missing.length){setRunMessage('Thiếu file: '+missing.join(', ')+'.','warn');return}
 try{setRunMessage('Bắt đầu đọc dữ liệu theo mô hình 2 luồng: Doanh thu/HĐ và Chi phí/Quyết toán...','info');const orders=await parseOrdersForEngine(uploadedFiles.orders);setRunMessage('Đã đọc '+orders.count.toLocaleString('vi-VN')+' dòng đơn hàng. Đang đọc Income...','info');const income=await parseIncomeForEngine(uploadedFiles.income);setRunMessage('Đã đọc '+income.count.toLocaleString('vi-VN')+' dòng Income. Đang đọc hóa đơn...','info');const invoice=await parseInvoiceForEngine(uploadedFiles.invoice);setRunMessage('Đã đọc '+invoice.count.toLocaleString('vi-VN')+' dòng hóa đơn. Đang ghép theo Order ID...','info');const rows=buildLiveRows(orders.map,income.map,invoice.map);window.__CURRENT_PERIOD_ROWS=rows;liveResultState.rows=rows;liveResultState.invoiceRows=rows;liveResultState.feesRows=rows;liveResultState.pages={dashboard:1,invoice:1,fees:1};renderV2();localStorage.setItem('nht_last_run_summary',JSON.stringify({at:new Date().toISOString(),version:V2,rows:rows.length}));setRunMessage('CHẠY XONG: '+rows.length.toLocaleString('vi-VN')+' Order ID. Đang lưu kỳ dữ liệu và cập nhật dữ liệu năm...','info');await saveCurrentPeriod(false);renderV2();setRunMessage('CHẠY XONG & ĐÃ CẬP NHẬT DỮ LIỆU NĂM. Income của đơn khác tháng vẫn được giữ theo Order ID/ngày đơn hàng để ghép ở các kỳ sau.','ok')}catch(err){console.error(err);setRunMessage('LỖI KHI CHẠY: '+(err?.message||err),'bad')}
};

let V2_REV=[],V2_COST=[];
function badgeRisk(v){return v==='CAO'?'bad':v==='TRUNG BÌNH'?'warn':'ok'}
function revenueFilter(){const rows=liveResultState.rows||[];const s=txt(q('v2RevSearch')?.value).toLowerCase(),st=txt(q('v2RevStatus')?.value),risk=txt(q('v2RevRisk')?.value);V2_REV=rows.filter(r=>r.revenue_in_period).filter(r=>(!s||txt(r.order_id).toLowerCase().includes(s)||txt(r.invoice_no).toLowerCase().includes(s))&&(!st||r.invoice_state_v2===st)&&(!risk||r.risk_level===risk))}
function costFilter(){const rows=liveResultState.rows||[];const s=txt(q('v2CostSearch')?.value).toLowerCase(),risk=txt(q('v2CostRisk')?.value);V2_COST=rows.filter(r=>r.income_source_present).filter(r=>(!s||txt(r.order_id).toLowerCase().includes(s))&&(!risk||r.risk_level===risk))}
function sum(rows,k){return rows.reduce((a,r)=>a+num(r[k]),0)}
function renderV2Dashboard(){const rows=liveResultState.rows||[],rev=rows.filter(r=>r.revenue_in_period),cost=rows.filter(r=>r.income_source_present);const set=(id,v)=>{if(q(id))q(id).textContent=typeof v==='number'?money(v):v};set('v2KpiRevenue',sum(rev,'required_invoice'));set('v2KpiInvoice',sum(rev,'invoice_compare_value'));set('v2KpiFees',sum(cost,'total_fee_calc'));set('v2KpiSettlement',sum(cost,'settlement'));set('v2KpiHigh',rows.filter(r=>r.risk_level==='CAO').length.toLocaleString('vi-VN'));set('v2KpiIncomeOnly',rows.filter(r=>r.income_source_present&&!r.order_source_present).length.toLocaleString('vi-VN'));const exceptions=rows.filter(r=>r.risk_level!=='THẤP').slice(0,300);if(q('v2RiskBody'))q('v2RiskBody').innerHTML=exceptions.map(r=>'<tr><td>'+escapeHtml(r.order_id)+'</td><td>'+escapeHtml(r.source_state)+'</td><td>'+escapeHtml(r.order_month||'')+'</td><td>'+escapeHtml(r.settlement_month||'')+'</td><td>'+escapeHtml(r.invoice_state_v2)+'</td><td><span class="badge '+badgeRisk(r.risk_level)+'">'+r.risk_level+'</span></td><td>'+escapeHtml(r.accounting_action||'')+'</td></tr>').join('')||'<tr><td colspan="7" class="muted">Không có ngoại lệ.</td></tr>'}
function renderV2Revenue(){revenueFilter();const body=q('v2RevenueBody');if(!body)return;body.innerHTML=V2_REV.map(r=>'<tr><td>'+escapeHtml(r.order_id)+'</td><td>'+escapeHtml(r.order_status)+'</td><td>'+escapeHtml(r.created)+'</td><td>'+escapeHtml(r.delivered)+'</td><td>'+money(r.sku_revenue)+'</td><td>'+money(r.order_shipping_buyer)+'</td><td>'+money(r.order_refund_amount)+'</td><td>'+money(r.required_invoice)+'</td><td>'+money(r.invoice_original_issued_amount)+'</td><td>'+money(r.invoice_adjustment_amount)+'</td><td>'+money(r.invoice_compare_value)+'</td><td>'+money(r.invoice_diff)+'</td><td>'+escapeHtml(r.invoice_state_v2)+'</td><td><span class="badge '+badgeRisk(r.risk_level)+'">'+r.risk_level+'</span></td><td>'+escapeHtml(r.accounting_action)+'</td></tr>').join('')||'<tr><td colspan="15" class="muted">Không có dữ liệu doanh thu thuộc kỳ.</td></tr>';if(q('v2RevenueCount'))q('v2RevenueCount').textContent=V2_REV.length.toLocaleString('vi-VN')+' đơn thuộc kỳ doanh thu';const states=[...new Set((liveResultState.rows||[]).filter(r=>r.revenue_in_period).map(r=>r.invoice_state_v2))].sort();const sel=q('v2RevStatus');if(sel){const cur=sel.value;sel.innerHTML='<option value="">Tất cả trạng thái HĐ</option>'+states.map(x=>'<option>'+escapeHtml(x)+'</option>').join('');sel.value=cur}}
function renderV2Cost(){costFilter();const body=q('v2CostBody');if(!body)return;body.innerHTML=V2_COST.map(r=>'<tr><td>'+escapeHtml(r.order_id)+'</td><td>'+escapeHtml(r.created||r.income_order_date)+'</td><td>'+escapeHtml(r.settlement_date)+'</td><td>'+money(r.seller_net)+'</td><td>'+money(r.buyer_shipping_income)+'</td><td>'+money(r.buyer_shipping_refund)+'</td><td>'+money(r.required_invoice_income)+'</td><td>'+money(r.transaction_fee)+'</td><td>'+money(r.tiktok_commission)+'</td><td>'+money(r.processing_fee)+'</td><td>'+money(r.shipping_actual)+'</td><td>'+money(r.shipping_platform_discount)+'</td><td>'+money(r.failed_delivery_subsidy)+'</td><td>'+money(r.return_shipping_actual)+'</td><td>'+money(r.affiliate)+'</td><td>'+money(r.partner)+'</td><td>'+money(r.adjustment)+'</td><td>'+money(r.total_fee_calc)+'</td><td>'+money(r.settlement)+'</td><td>'+money(r.settlement_calc)+'</td><td>'+money(r.settlement_diff)+'</td><td>'+escapeHtml(r.order_month||'')+'</td><td>'+escapeHtml(r.settlement_month||'')+'</td><td>'+escapeHtml(r.source_state)+'</td><td><span class="badge '+badgeRisk(r.risk_level)+'">'+r.risk_level+'</span></td></tr>').join('')||'<tr><td colspan="25" class="muted">Không có dữ liệu Income.</td></tr>';if(q('v2CostCount'))q('v2CostCount').textContent=V2_COST.length.toLocaleString('vi-VN')+' Order ID trong Income kỳ này'}
function renderV2(){renderV2Dashboard();renderV2Revenue();renderV2Cost()}
window.v2ApplyRevenue=()=>renderV2Revenue();window.v2ApplyCost=()=>renderV2Cost();window.v2ExportRevenue=()=>objectRowsToXlsx(V2_REV,'DOI_CHIEU_DOANH_THU_HOA_DON.xlsx','Doanh thu - HĐ',true);window.v2ExportCost=()=>objectRowsToXlsx(V2_COST,'DOI_CHIEU_CHI_PHI_QUYET_TOAN.xlsx','Chi phí - Quyết toán',true);

function installV2UI(){
 const notice=q('standaloneNotice');if(notice)notice.innerHTML='Mô hình kế toán 2 luồng: <b>Đơn hàng + Hóa đơn = Đối chiếu doanh thu</b> · <b>Income = Đối chiếu chi phí & quyết toán</b>. Income của đơn khác tháng vẫn được lưu theo Order ID để cập nhật xuyên năm.';
 const invNav=document.querySelector('[data-page="invoice"]');if(invNav)invNav.textContent='Đối chiếu doanh thu';const feeNav=document.querySelector('[data-page="fees"]');if(feeNav)feeNav.textContent='Chi phí & quyết toán';
 const dash=q('dashboard');if(dash)dash.innerHTML=[
 '<div class="card section"><h2>Tổng quan kiểm soát kế toán</h2><div class="muted">Tách riêng 2 luồng: (1) doanh thu/hóa đơn theo ngày giao hàng từ file Tất cả đơn hàng; (2) chi phí/quyết toán theo file Income. Không loại bỏ Income của đơn khác tháng.</div></div>',
 '<div class="kpis section" style="grid-template-columns:repeat(3,minmax(170px,1fr))">',
 '<div class="card kpi"><span class="muted">Doanh thu cần xuất HĐ (Orders)</span><b id="v2KpiRevenue">0</b></div>',
 '<div class="card kpi"><span class="muted">HĐ hiệu lực đã xuất</span><b id="v2KpiInvoice">0</b></div>',
 '<div class="card kpi"><span class="muted">Tổng chi phí sàn</span><b id="v2KpiFees">0</b></div>',
 '<div class="card kpi"><span class="muted">TikTok quyết toán</span><b id="v2KpiSettlement">0</b></div>',
 '<div class="card kpi"><span class="muted">Rủi ro cao</span><b id="v2KpiHigh">0</b></div>',
 '<div class="card kpi"><span class="muted">Income chưa có đơn gốc</span><b id="v2KpiIncomeOnly">0</b></div></div>',
 '<div class="card section"><h2>Ngoại lệ cần kế toán xử lý</h2><div class="tablewrap"><table><thead><tr><th>Order ID</th><th>Nguồn</th><th>Tháng đơn</th><th>Tháng quyết toán</th><th>Trạng thái HĐ</th><th>Rủi ro</th><th>Hành động</th></tr></thead><tbody id="v2RiskBody"></tbody></table></div></div>'
 ].join('');
 const inv=q('invoice');if(inv)inv.innerHTML=[
 '<div class="card section"><h2>Đối chiếu doanh thu & hóa đơn</h2><div class="muted"><b>File gốc:</b> Tất cả đơn hàng. Chỉ đơn đã giao/hoàn tất có ngày giao thuộc kỳ mới vào doanh thu tháng. Danh sách hóa đơn dùng để xác định đã xuất đủ, dư, thiếu, cần điều chỉnh và đã điều chỉnh chưa.</div></div>',
 '<div class="card section"><div class="toolbar"><input id="v2RevSearch" placeholder="Order ID / số HĐ" oninput="v2ApplyRevenue()"><select id="v2RevStatus" onchange="v2ApplyRevenue()"><option value="">Tất cả trạng thái HĐ</option></select><select id="v2RevRisk" onchange="v2ApplyRevenue()"><option value="">Tất cả mức rủi ro</option><option>CAO</option><option>TRUNG BÌNH</option><option>THẤP</option></select><button class="btn primary" onclick="v2ExportRevenue()">Xuất Excel</button><span id="v2RevenueCount" class="muted"></span></div>',
 '<div class="tablewrap"><table><thead><tr><th>Order ID</th><th>Trạng thái đơn</th><th>Ngày đơn</th><th>Ngày giao</th><th>DT SKU sau giảm</th><th>VC người mua</th><th>Hoàn đơn</th><th>GT cần xuất HĐ</th><th>HĐ lần đầu</th><th>HĐ điều chỉnh</th><th>HĐ hiệu lực</th><th>Chênh HĐ</th><th>Trạng thái HĐ</th><th>Rủi ro</th><th>Hành động kế toán</th></tr></thead><tbody id="v2RevenueBody"></tbody></table></div></div>'
 ].join('');
 const fees=q('fees');if(fees)fees.innerHTML=[
 '<div class="card section"><h2>Đối chiếu chi phí & tiền quyết toán TikTok</h2><div class="muted">Income là chi tiết khoản TikTok quyết toán trong kỳ. Mọi Order ID trong Income đều được lưu, kể cả đơn có ngày đơn ở tháng khác; khi file đơn tháng gốc được nhập sau, hệ thống ghép lại theo Order ID.</div></div>',
 '<div class="card section"><div class="toolbar"><input id="v2CostSearch" placeholder="Order ID" oninput="v2ApplyCost()"><select id="v2CostRisk" onchange="v2ApplyCost()"><option value="">Tất cả mức rủi ro</option><option>CAO</option><option>TRUNG BÌNH</option><option>THẤP</option></select><button class="btn primary" onclick="v2ExportCost()">Xuất Excel</button><span id="v2CostCount" class="muted"></span></div>',
 '<div class="tablewrap"><table><thead><tr><th>Order ID</th><th>Ngày đơn</th><th>Ngày quyết toán</th><th>DT hàng sau hoàn</th><th>VC người mua</th><th>Hoàn VC người mua</th><th>Doanh thu Income</th><th>Phí giao dịch</th><th>HH TikTok</th><th>Phí xử lý</th><th>VC thực tế</th><th>CK VC nền tảng</th><th>Trợ cấp giao thất bại</th><th>VC trả hàng</th><th>Affiliate</th><th>Đối tác</th><th>Điều chỉnh</th><th>Tổng chi phí</th><th>TikTok quyết toán</th><th>Quyết toán tự tính</th><th>Chênh QT</th><th>Tháng đơn</th><th>Tháng QT</th><th>Nguồn</th><th>Rủi ro</th></tr></thead><tbody id="v2CostBody"></tbody></table></div>',
 '<div class="note" style="margin-top:10px">Gợi ý hạch toán: Doanh thu N131-Sàn/C511,C3331; từng loại phí N641/642/C131-Sàn; tiền TikTok chuyển về N112/C131-Sàn. Thuế GTGT đầu vào của phí chỉ ghi nhận khi có hóa đơn/chứng từ hợp lệ.</div></div>'
 ].join('');
 const upload=q('upload');if(upload){const first=upload.querySelector('.card.section');if(first){const n=document.createElement('div');n.className='note';n.style.marginBottom='12px';n.innerHTML='<b>Quy tắc V2:</b> Tất cả đơn hàng = nguồn gốc doanh thu/HĐ theo ngày giao. Income = nguồn chi phí/quyết toán; không lọc bỏ đơn khác tháng. Danh sách HĐ = vòng đời HĐ gốc/điều chỉnh/thay thế.';first.prepend(n)}}
 renderV2();
}
document.addEventListener('DOMContentLoaded',()=>setTimeout(installV2UI,200));window.addEventListener('load',()=>setTimeout(renderV2,1200));
})();